// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as React from "react";
import * as ReactDOMRe from "reason-react/src/legacy/ReactDOMRe.bs.js";
import * as App$ReasonTodomvc from "./App.bs.js";

ReactDOMRe.renderToElementWithId(React.createElement(App$ReasonTodomvc.make, {}), "root");

export {
  
}
/*  Not a pure module */
